retention: 24h
storage:
    capacity: 30G
    storageClassName: local-path
tempo:
  image: grafana/tempo:0.3.0
  resources: 
    requests:
      cpu:      1
      memory:   4Gi
  receivers:
    jaeger:
      protocols:
        thrift_http: null
tempoQuery:
  image: grafana/tempo-query:0.3.0
  resources: 
    requests:
      cpu:      50m
      memory:   100Mi